### ISSUE TITLE
[버그] 설정에서 X 버튼 누르면 제대로 작동안하는 현상

### ISSUE THREAD

**Issue by bugtype** [techinpark/upbitBar#3]
### Flow

- 설정 -> [x] 버튼 선택 -> 다시 [설정] 을 누르지 못한다.
  - 닫기or 저장 누를 시에는 정상적으로 작동하나. 버튼이 active 상태가 아니다.

### 기대하는 결과

- 다시 설정을 누를 수 있어야 한다. ( 현재는 종료만 가능 )

**Comment by dev-jason-hwkim** [comment]
@bugtype 해당이슈 수정 되었습니다.

**Comment by bugtype** [comment]
Thank you for solving it. 👍
